#!/usr/bin/env bash

selected=$(fd . --base-directory "$HOME/code" --exact-depth 1 --type d --strip-cwd-prefix | fzf --tmux)

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename $selected | tr ":,. " "____")

switch_to() {
	if [[ -z "$TMUX" ]]; then
		tmux attach-session -t $selected_name
	else
		tmux switch-client -t $selected_name
	fi
}

if tmux has-session -t=$selected_name 2> /dev/null; then
	switch_to
	exit 0
fi

tmux new-session -ds $selected_name -c "$HOME/code/$selected"
tmux send-keys -t "$selected_name:1.0" "ready-tmux" C-m 
switch_to
