#!/usr/bin/env bash

set -euo pipefail

log() {
	echo "$@"
}

execute() {
	log "execute $@"
	"$@"
}

log "Bootstrapping..."
curl -fsSL https://raw.githubusercontent.com/paultibbetts/dev/main/runs/00-bootstrap/00-xcode-cl-tools | bash

log "Preparing..."
mkdir -p ~/code/

if [[ -d "$HOME/code/dev" ]]; then
    cd ~/code/dev
    git pull
else
    git clone https://github.com/paultibetts/dev.git ~/code/dev
fi

cd ~/code/dev

log "Installing..."
execute ./run

log "Done!"
