#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry=""
bootstrap=""

while [[ $# > 0 ]]; do
	if [[ $1 == "--dry" ]]; then
		dry="1"
	elif [[ $1 == "--bootstrap" ]]; then
		bootstrap="1"
	else
		filter="$1"
	fi
	shift
done

log() {
	if [[ $dry == "1" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo "$@"
	fi
}

execute() {
	log "execute $@"
	if [[ $dry == "1" ]]; then
		return
	fi

	"$@"
}

log "$script_dir -- $filter"

cd $script_dir

if [[ $bootstrap == "1" || $filter == "bootstrap" ]]; then
	execute ./runs/bootstrap/run ${dry:+--dry}
fi

if [[ $filter == "bootstrap" ]]; then
	exit 0;
fi

scripts=$(find ./runs/system ./runs/apps -mindepth 1 -maxdepth 1 -type f -perm +111)

for script in $scripts; do
	if echo "$script" | grep -qv "$filter"; then
		log "filtering $script"
		continue
	fi

	execute ./$script
done
