#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry=""
bootstrap=""

while [[ $# > 0 ]]; do
	if [[ $1 == "--dry" ]]; then
		dry="1"
	elif [[ $1 == "--bootstrap" ]]; then
		bootstrap="1"
	else
		filter="$1"
	fi
	shift
done

log() {
	if [[ $dry == "1" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo "$@"
	fi
}

execute() {
	log "execute $@"
	if [[ $dry == "1" ]]; then
		return
	fi

	"$@"
}

log "$script_dir -- $filter"

cd $script_dir

dirs=()

if [[ $bootstrap == "1" || $filter == "bootstrap" ]]; then
	dirs=("./runs/00-bootstrap")
else
	dirs=("./runs/10-system" "./runs/20-runtimes" "./runs/30-tools")
fi

for dir in "${dirs[@]}"; do
	scripts=$(find "$dir" -mindepth 1 -maxdepth 1 -type f -perm -111 | sort)
	for script in $scripts; do
		if [[ -n "$filter" && "$script" != *"$filter"* ]]; then
			continue
		fi

		execute ./$script
	done
done
