#!/usr/bin/env bash

GO_VERSION="1.24.3"
ARCH="arm64"
OS="darwin"
curl -LO "https://go.dev/dl/go${GO_VERSION}.${OS}-${ARCH}.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go${GO_VERSION}.${OS}-${ARCH}.tar.gz"
rm "go${GO_VERSION}.${OS}-${ARCH}.tar.gz"

