#!/usr/bin/env bash

if [[ -x "$(command -v brew)" ]]; then
	echo "Homebrew is already installed."
	exit 0
fi

sudo -v

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
